### ISSUE TITLE
Incompatiblity on .net core on linux

### ISSUE THREAD

**Issue by MaxCheetham** [jamesmanning/RunProcessAsTask#15]
The travis failure indicates a possibly real incompatiblity on .net core on linux; the message being:

```
Unhandled Exception: System.ComponentModel.Win32Exception: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.
   at System.Diagnostics.Process.GetStat()
   at System.Diagnostics.Process.get_StartTime()
```

That looks like it's the following corefx issue: https://github.com/dotnet/corefx/issues/13210

**Comment by jamesmanning** [comment]
Since the referenced issue is talking about a failure in TestStartTimeProperty, is the issue with start time or exit time or both?  Not that it really matters - IMHO it's fine to take the route @EamonNerbonne referred to and just leave our code as-is and let the underlying framework deal with the problem.

**Comment by MaxCheetham** [comment]
Hmm, Thats interesting. I just assumed that the error was Exit Time becuase that was what i ran into before. i'll spin up a vagrant box and have a little play with it and see where we get to. I just wanted to have the issue created incase any users run into the problem.

**Comment by MaxCheetham** [comment]
[Travis Build](https://travis-ci.org/jamesmanning/RunProcessAsTask/builds/224991726) for https://github.com/jamesmanning/RunProcessAsTask/commit/70bd600200a449c1ca032bdec4f28c769cf1dea4 is throwing `Actual:   String[] ["No executable found matching command \"dotnet-Dumm"...]` Going to give `dotnet run` a go.

**Comment by MaxCheetham** [comment]
Closing for now due to lack of update.

**Comment by nathanaeljones** [comment]
I'm still getting this

**Comment by nathanaeljones** [comment]
Process.StartTime cannot be accessed after the process exits. This [is documented](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.starttime(v=vs.110).aspx). The ProcessResults constructor accesses this property regardless of state.

**Comment by jamesmanning** [comment]
@nathanaeljones I've pushed a potential fix with commit e20469c696d723e2b092ebf6345a02435923d36e but tests aren't running locally for me at the moment - I'm working on that now but wanted to let you know about the commit in case it unblocks you.

**Comment by jamesmanning** [comment]
@nathanaeljones the tests pass when I run 'dotnet test' locally, so hopefully this change will be sufficient for you.  I'm going to see if I can get the tests working on the CI build now.

![image](https://user-images.githubusercontent.com/225626/31865550-5472d412-b73e-11e7-8a13-ecf2998acf08.png)

**Comment by damonbarry** [comment]
I ran into this same problem in a netcoreapp2.0 project that uses v1.2.0 of your NuGet package. If I build the RunProcessAsTask library myself (from `master`) instead of pulling in the NuGet package, it works fine.

Are you going to publish an updated NuGet package soon?

**Comment by jamesmanning** [comment]
@damonbarry good idea, I just pushed version 1.2.1 from master, can you give it a shot, please?

**Comment by damonbarry** [comment]
@jamesmanning Works great, thanks!
