### ISSUE TITLE
Add `ConfigureAwait(false)` to all awaits

### ISSUE THREAD

**Issue by ronaldbarendse** [jamesmanning/RunProcessAsTask#18]
To prevent deadlocks, all internal awaited tasks should use `ConfigureAwait(false)`, see:
- https://msdn.microsoft.com/en-us/magazine/jj991977.aspx
- https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
- https://github.com/Tyrrrz/CliWrap/blob/master/CliWrap/Cli.cs (similar library)

**Comment by jamesmanning** [comment]
@ronaldbarendse @EamonNerbonne given that it seems to be a superset of functionality, I'm inclined to kill this project and point to the https://github.com/Tyrrrz/CliWrap project that Ronald pointed out instead.  Thoughts?

**Comment by EamonNerbonne** [comment]
Do you have a specific scenario in which this causes deadlocks, or is this theoretical?

Although using configureawait everywhere is sufficient to prevent single-threaded sync contexts from deadlocking, it's usually overkill (not that that's a huge problem here).

**Comment by ronaldbarendse** [comment]
This library has a better and leaner API IMHO, especially because it uses `ProcessStartInfo` and therefore be fairly simple to replace in existing code.

I did get some deadlocks when using `.Result` in an event handler on a web application (that had to run synchronously, because the process output was needed). I'll test again after the PR is merged back in and a new version released!

**Comment by jamesmanning** [comment]
@ronaldbarendse version 1.2.2 now published with your PR merged if you want to give it a shot.

**Comment by ronaldbarendse** [comment]
Thanks @jamesmanning! No deadlocks anymore 👍
