### ISSUE TITLE
Cannot capture the process output

### ISSUE THREAD

**Issue by SuperJMN** [jamesmanning/RunProcessAsTask#21]
I'm thinking of adding these 2 to the method signature:

`IObserver<string> outputObserver = null, IObserver<string> errorObserver = null`

**Comment by jamesmanning** [comment]
Maybe just use the CliWrap project instead? I'd rather not scope creep when
there's already an alternative that covers that use case, imho. That
project covers many more use cases.  😊

https://github.com/Tyrrrz/CliWrap

https://www.nuget.org/packages/CliWrap/

**Comment by EamonNerbonne** [comment]
To really wrap a cli, you'll want to preserve the interleaving of stderr and stdout - even though that's an intrinsic race-condition.  After all, many CLI apps write to both stderr and stdout, and in an order that may well matter.

I don't believe cliWrap actually does that, and even if it did - it's not using IObservable, so actually registering code to execute just-in-time when there's output available is a pain.

**Comment by jamesmanning** [comment]
I'm going to add a comment into the README about it but I think there's enough available alternatives (CliWrap, Process directly) that I'd rather keep handling/observing the stdout/stderr outside the scope of this particular project.
