### ISSUE TITLE
Add netstandard2.0 target

### ISSUE THREAD

**Issue by hanabi1224** [jamesmanning/RunProcessAsTask#25]
It's recommended to always target netstandard2.0 per https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

![image](https://user-images.githubusercontent.com/6546635/59160671-11243f00-8b0b-11e9-8c5f-c636d76323cb.png)

**Comment by jamesmanning** [comment]
resolving as dupe of 26

**Comment by jamesmanning** [comment]
@hanabi1224 the 1.2.4 version is up on nuget and includes .net standard 2.0 now - thanks for the pull request!!
