### ISSUE TITLE
git clone issue using RunProcessAsTask 

### ISSUE THREAD

**Issue by Legends** [jamesmanning/RunProcessAsTask#28]
I am running a `git clone myrepoUrl` using this project, the cloning works fine,
but why does the `processResults.StandardError` contain the `StandardOutput` message?

**Code to reproduce issue:**

```
static async Task Main(string[] args)
{
	// Synchronous, just easier way of grabbing output / error / runtime for the process
	var processResults = await ProcessEx.RunAsync("git.exe", "clone https://github.com/Legends/File-Loader-Issue.git");
	//new ProcessStartInfo("",)
	Console.WriteLine("Exit code: " + processResults.ExitCode);
	Console.WriteLine("Run time: " + processResults.RunTime);

	Console.WriteLine("{0} lines of standard output", processResults.StandardOutput.Length);
	foreach (var output in processResults.StandardOutput) // <-- message should be here
	{
		Console.WriteLine("Output line: " + output);
	}

	Console.WriteLine("{0} lines of standard error", processResults.StandardError.Length);
	foreach (var error in processResults.StandardError) // <-- why is the message here
	{
		Console.WriteLine("Error line: " + error); 
	}
}
```

**Comment by EamonNerbonne** [comment]
By default, git reports progress output to standard error, not output.  You can use [`git clone --quiet`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---quiet) to turn off that reporting.

**Comment by EamonNerbonne** [comment]
(Thanks for the detailed repro BTW!)

**Comment by Legends** [comment]
He, really?! And when an error occurs git reports to `StandardOutput`?
Doesn't make sense to me, but ok. Is it only with `git` like this or the same with other tools?

**Comment by Trolldemorted** [comment]
[Other tools](https://stackoverflow.com/questions/6935006/making-curl-send-errors-to-stderr-and-everything-else-to-stdout) [do this too](https://superuser.com/questions/420120/wget-is-silent-but-it-displays-error-messages).

It enables users to pipe the clean result output into something while displaying status information at the same time.

**Comment by Legends** [comment]
Thanks for the infos!
