### ISSUE TITLE
Nondeterministically fails when process prints and exits in quick succession

### ISSUE THREAD

**Issue by EamonNerbonne** [jamesmanning/RunProcessAsTask#3]
This stackoverflow question describes the issue:

 http://stackoverflow.com/questions/63303/how-do-i-know-when-the-last-outputdatareceived-has-arrived

In short: the current implementation may truncate captured standard error and standard output in such a scenario.

Also, although multiple output and error events are executed synchronously, I'm not sure that's the case for process exit and output events.  Are you sure it's thread-safe to call `List<>.ToArray()` in the `Process.Exit` event handler?

**Comment by jamesmanning** [comment]
Thanks for reporting this @EamonNerbonne !  I've been able to repro it locally, so working on a fix now.

**Comment by EamonNerbonne** [comment]
No hurry - please enjoy your weekend too!

It's a shame a the `Process` api is such a minefield - but hey, that sure underlines the need for a project such as this!
